services:
  - type: web
    name: news-api
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
      - key: TABLE_NEWS
